/* ============================================================================
   DE Architects — languages
   ----------------------------------------------------------------------------
   Six languages, two of them right-to-left. The English copy stays in the HTML
   as the source of truth; every other language is a dictionary keyed off it
   (js/lang/*.js, generated and re-generated by tools/i18n_extract.py).

   Loading is lazy and by <script> tag rather than fetch, so the site still
   works opened straight off disk with no server — which is how people preview
   a static build.

   Three kinds of mark-up are honoured:

     data-i18n            swap the element's text, leave child elements alone,
                          so a button keeps its icon
     data-i18n-html       swap the inner markup; {{0}} tokens are refilled with
                          the SVGs already in the element, so an arrow can move
                          to the other side of the words in Arabic or Urdu
     data-i18n-attr-*     swap an attribute (placeholder, aria-label, title, alt)

   English needs no dictionary: the original text is cached on first run and
   restored when you switch back, so nothing is lost in a round trip.
   ========================================================================== */
(() => {
  const LANGS = {
    en: { label: 'English',  native: 'English',  dir: 'ltr' },
    ur: { label: 'Urdu',     native: 'اردو',      dir: 'rtl' },
    ar: { label: 'Arabic',   native: 'العربية',    dir: 'rtl' },
    de: { label: 'German',   native: 'Deutsch',  dir: 'ltr' },
    fr: { label: 'French',   native: 'Français', dir: 'ltr' },
    es: { label: 'Spanish',  native: 'Español',  dir: 'ltr' }
  };
  const KEY = 'de-lang';
  const DEFAULT = 'en';

  window.DE_I18N = window.DE_I18N || {};
  const loaded = { en: true };          // English is the markup itself

  /* --- what the original page said, so English is always recoverable ------ */
  const original = new WeakMap();

  function snapshot(el, kind, name) {
    let rec = original.get(el);
    if (!rec) { rec = {}; original.set(el, rec); }
    const slot = name ? 'attr:' + name : kind;
    if (!(slot in rec)) {
      rec[slot] = name ? el.getAttribute(name)
                : kind === 'html' ? el.innerHTML
                : textOf(el);
    }
    return rec[slot];
  }

  /* --- text mode: replace the element's own words, keep its children ------ */
  function textOf(el) {
    let out = '';
    for (const n of el.childNodes) if (n.nodeType === 3) out += n.nodeValue;
    return out.replace(/\s+/g, ' ').trim();
  }

  function setText(el, value) {
    const texts = [...el.childNodes].filter(n => n.nodeType === 3);
    const first = texts.find(n => n.nodeValue.trim()) || texts[0];
    if (!first) { el.prepend(document.createTextNode(value)); return; }
    // keep whatever spacing sat around the word, so "Menu <svg>" stays spaced
    const lead = /^\s*/.exec(first.nodeValue)[0];
    const tail = /\s*$/.exec(first.nodeValue)[0];
    first.nodeValue = lead + value + tail;
    for (const n of texts) if (n !== first && n.nodeValue.trim()) n.nodeValue = '';
  }

  /* --- html mode: refill {{n}} with the icons already in the element ------ */
  function setHTML(el, value, icons) {
    el.innerHTML = value.replace(/\{\{(\d+)\}\}/g, (m, i) => icons[+i] || '');
  }

  function iconsOf(el) {
    let rec = original.get(el);
    if (!rec) { rec = {}; original.set(el, rec); }
    if (!rec.icons) {
      rec.icons = [...el.querySelectorAll('svg')].map(s => s.outerHTML);
    }
    return rec.icons;
  }

  /* --- applying a whole page --------------------------------------------- */
  function apply(lang) {
    const dict = lang === 'en' ? null : (window.DE_I18N[lang] || {});
    const miss = [];

    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.dataset.i18n;
      const src = snapshot(el, 'text');
      const val = dict ? dict[key] : src;
      if (dict && !dict[key]) { miss.push(key); setText(el, src); return; }
      setText(el, val);
    });

    document.querySelectorAll('[data-i18n-html]').forEach(el => {
      const key = el.dataset.i18nHtml;
      const src = snapshot(el, 'html');
      const icons = iconsOf(el);
      const val = dict ? dict[key] : src;
      if (dict && !dict[key]) { miss.push(key); el.innerHTML = src; return; }
      setHTML(el, val, icons);
    });

    for (const attr of ['placeholder', 'aria-label', 'title', 'alt']) {
      const prop = 'i18nAttr' + attr.replace(/(^|-)([a-z])/g, (m, d, c) => c.toUpperCase());
      document.querySelectorAll(`[data-${'i18n-attr-' + attr}]`).forEach(el => {
        const key = el.dataset[prop];
        if (!key) return;
        const src = snapshot(el, 'attr', attr);
        const val = dict ? dict[key] : src;
        if (dict && !dict[key]) { miss.push(key); el.setAttribute(attr, src); return; }
        el.setAttribute(attr, val);
      });
    }

    const meta = LANGS[lang] || LANGS[DEFAULT];
    const html = document.documentElement;
    html.setAttribute('lang', lang);
    html.setAttribute('dir', meta.dir);
    html.classList.toggle('is-rtl', meta.dir === 'rtl');
    html.classList.toggle('font-ur', lang === 'ur');
    html.classList.toggle('font-ar', lang === 'ar');
    if (lang === 'ur' || lang === 'ar') needFont(lang);

    if (miss.length) {
      console.warn(`[i18n] ${miss.length} key(s) missing for "${lang}" — ` +
                   `English shown for those. First few: ${miss.slice(0, 5).join(', ')}`);
    }
    document.dispatchEvent(new CustomEvent('de:lang', { detail: { lang, dir: meta.dir } }));
  }

  /* --- the Arabic and Urdu faces ------------------------------------------
     Anton, Archivo and Inter carry no Arabic script at all, so those two
     languages need their own faces or the page renders in whatever fallback
     the machine happens to have. They are fetched only when one of the two is
     actually chosen — an English visitor never pays for them. */
  const FONTS = {
    ar: 'https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;900&family=Noto+Kufi+Arabic:wght@400;600;700&display=swap',
    ur: 'https://fonts.googleapis.com/css2?family=Noto+Nastaliq+Urdu:wght@400;600;700&family=Noto+Naskh+Arabic:wght@400;600;700&display=swap'
  };
  const fontDone = {};

  function needFont(lang) {
    if (fontDone[lang] || !FONTS[lang]) return;
    fontDone[lang] = true;
    const link = document.createElement('link');
    link.rel = 'stylesheet';
    link.href = FONTS[lang];
    document.head.appendChild(link);
  }

  /* --- translating strings that are not in the markup ----------------------
     The project titles and copy live in js/projects-data.js and are rendered
     after this file runs, so they never carry a data-i18n attribute. en.js
     doubles as a reverse index — English text back to its key — which lets
     the render code ask for a translation by passing the English string. */
  let REV = null;

  function t(text) {
    if (current === DEFAULT || typeof text !== 'string') return text;
    if (!REV) {
      REV = new Map();
      const en = window.DE_I18N.en || {};
      for (const k in en) REV.set(en[k], k);
    }
    const key = REV.get(text) || REV.get(text.trim());
    const dict = window.DE_I18N[current];
    return (key && dict && dict[key]) || text;
  }

  /* --- loading a dictionary ---------------------------------------------- */
  function load(lang) {
    if (loaded[lang] || lang === 'en') return Promise.resolve(true);
    return new Promise(resolve => {
      const s = document.createElement('script');
      s.src = `js/lang/${lang}.js`;
      s.onload = () => { loaded[lang] = true; resolve(true); };
      s.onerror = () => {
        console.error(`[i18n] could not load js/lang/${lang}.js — staying on English`);
        resolve(false);
      };
      document.head.appendChild(s);
    });
  }

  async function set(lang, remember = true) {
    if (!LANGS[lang]) lang = DEFAULT;
    if (!(await load(lang))) lang = DEFAULT;
    if (remember) { try { localStorage.setItem(KEY, lang); } catch (e) { /* private mode */ } }
    current = lang;
    apply(lang);
    paintSwitch();
  }

  /* --- which language to open on ----------------------------------------- */
  function preferred() {
    const q = new URLSearchParams(location.search).get('lang');
    if (q && LANGS[q]) return q;
    try {
      const saved = localStorage.getItem(KEY);
      if (saved && LANGS[saved]) return saved;
    } catch (e) { /* private mode */ }
    for (const tag of navigator.languages || [navigator.language || '']) {
      const base = String(tag).toLowerCase().split('-')[0];
      if (LANGS[base]) return base;
    }
    return DEFAULT;
  }

  let current = DEFAULT;

  /* --- the switcher, in the navbar where search used to be ---------------- */
  function paintSwitch() {
    document.querySelectorAll('.lang-switch').forEach(box => {
      const code = box.querySelector('.lang-code');
      if (code) code.textContent = current.toUpperCase();
      box.querySelectorAll('.lang-menu button').forEach(b => {
        const on = b.dataset.lang === current;
        b.classList.toggle('is-on', on);
        b.setAttribute('aria-checked', on ? 'true' : 'false');
      });
      const btn = box.querySelector('.lang-btn');
      if (btn) btn.setAttribute('aria-label', `Language: ${LANGS[current].label}`);
    });
  }

  function buildSwitch(box) {
    box.innerHTML =
      `<button class="lang-btn" type="button" aria-haspopup="true" aria-expanded="false">
         <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
           <circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 010 18 15 15 0 010-18"/>
         </svg>
         <span class="lang-code">EN</span>
       </button>
       <div class="lang-menu" role="menu" hidden>` +
      Object.entries(LANGS).map(([code, m]) =>
        `<button type="button" role="menuitemradio" aria-checked="false" data-lang="${code}" lang="${code}">
           <span class="lang-native"${m.dir === 'rtl' ? ' dir="rtl"' : ''}>${m.native}</span>
           <span class="lang-label">${m.label}</span>
         </button>`).join('') +
      `</div>`;

    const btn = box.querySelector('.lang-btn');
    const menu = box.querySelector('.lang-menu');

    const close = () => { menu.hidden = true; btn.setAttribute('aria-expanded', 'false'); };
    const open = () => { menu.hidden = false; btn.setAttribute('aria-expanded', 'true'); };

    btn.addEventListener('click', e => {
      e.stopPropagation();
      menu.hidden ? open() : close();
    });
    menu.addEventListener('click', e => {
      const b = e.target.closest('button[data-lang]');
      if (!b) return;
      close();
      set(b.dataset.lang);
    });
    document.addEventListener('click', e => { if (!box.contains(e.target)) close(); });
    document.addEventListener('keydown', e => { if (e.key === 'Escape') close(); });
  }

  /* --- go ----------------------------------------------------------------- */
  function init() {
    document.querySelectorAll('.lang-switch').forEach(buildSwitch);
    const want = preferred();
    if (want === DEFAULT) { paintSwitch(); return; }   // page is already English
    set(want, false);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

  // small surface for the rest of the site and for debugging
  window.DELang = {
    get current() { return current; },
    set,
    t,
    langs: LANGS,
    dir: () => LANGS[current].dir
  };
})();
