/* Turn the human-editable translation files into the ones the site loads.
   ---------------------------------------------------------------------------
   js/lang/src/<code>.json is written as English -> translation, because that
   is what a translator can actually work with. The site needs key ->
   translation, and the keys are content hashes nobody should be typing by
   hand. This maps one to the other using en.js, and says what is missing.

       node tools/i18n-build.mjs          # build every language it finds
       node tools/i18n-build.mjs de fr    # or just these

   A string that has no translation is left out of the output rather than
   copied from English, so the runtime warns about it instead of quietly
   showing English as though it were finished work.
*/
import fs from 'node:fs';
import path from 'node:path';

global.window = {};
new Function('window', fs.readFileSync('js/lang/en.js', 'utf8'))(global.window);
const EN = global.window.DE_I18N.en;

// English text -> key
const REV = new Map();
for (const k of Object.keys(EN)) REV.set(EN[k], k);

const dir = 'js/lang/src';
const want = process.argv.slice(2);
const files = fs.existsSync(dir)
  ? fs.readdirSync(dir).filter(f => f.endsWith('.json')).map(f => f.replace('.json', ''))
  : [];
const codes = want.length ? want : files;

if (!codes.length) { console.log('nothing in js/lang/src to build'); process.exit(0); }

let bad = 0;
for (const code of codes) {
  const file = path.join(dir, code + '.json');
  if (!fs.existsSync(file)) { console.log(`  ${code}  no ${file}`); bad++; continue; }

  const pairs = JSON.parse(fs.readFileSync(file, 'utf8'));
  const out = {};
  const unknown = [];

  for (const [english, translated] of Object.entries(pairs)) {
    const key = REV.get(english);
    if (!key) { unknown.push(english); continue; }
    if (translated && translated !== '') out[key] = translated;
  }

  const missing = Object.keys(EN).filter(k => !(k in out));
  const pct = Math.round((Object.keys(out).length / Object.keys(EN).length) * 100);

  fs.writeFileSync(`js/lang/${code}.js`,
    `/* ${code} — built from js/lang/src/${code}.json by tools/i18n-build.mjs.\n` +
    `   Edit the .json and rebuild; do not edit this file. */\n` +
    'window.DE_I18N = window.DE_I18N || {};\n' +
    `window.DE_I18N.${code} = ${JSON.stringify(out, null, 1)};\n`, 'utf8');

  console.log(`  ${code}  ${Object.keys(out).length}/${Object.keys(EN).length} strings (${pct}%)` +
              (missing.length ? `, ${missing.length} untranslated` : ', complete') +
              (unknown.length ? `, ${unknown.length} stale entries no longer on the site` : ''));
  if (unknown.length) unknown.slice(0, 3).forEach(u => console.log(`      stale: ${JSON.stringify(u.slice(0, 60))}`));
  if (missing.length && missing.length <= 5) missing.forEach(m => console.log(`      todo: ${JSON.stringify(EN[m].slice(0, 60))}`));
}
process.exit(bad ? 1 : 0);
